post_install do |installer|
    target = installer.project.targets.find { |t| t.to_s == "Pods-Tests-Specta" }
    if (target)
        target.build_configurations.each do |config|
            s = config.build_settings['FRAMEWORK_SEARCH_PATHS']
            s = [ '$(inherited)' ] if s == nil;
            s.push('$(PLATFORM_DIR)/Developer/Library/Frameworks')
            config.build_settings['FRAMEWORK_SEARCH_PATHS'] = s
        end
    else
        puts "WARNING: Pods-Tests-Specta target not found"
    end
end

target :Tests do
	pod 'Specta',             	'~> 0.2.1'
	pod 'Expecta',            	'~> 0.3.0'
	pod 'OCMockito',          	'~> 1.3.0'
	pod 'NSURL+IDN',			'~> 0.3'
	inhibit_all_warnings!
end